# Generated by Django 1.11.4 on 2017-08-29 06:16
from django.db import migrations, models
import django.db.models.manager
import fiber.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=255, upload_to=fiber.models.files_directory, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=255, upload_to=fiber.models.images_directory, verbose_name='image'),
        ),
    ]
