# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiber', '0002_auto_20160629_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(default='', max_length=255, upload_to='uploads/images', verbose_name='image'),
            preserve_default=False,
        ),
    ]
