# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiber', '0003_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='count_page',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Count url'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=255, upload_to='uploads/images', verbose_name='image'),
        ),
    ]
