# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.6, 3.7, 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install tox tox-gh-actions
      - name: Run tests
        run: tox
      - name: Coverage
        if: ${{ matrix.python == 3.8 }}
        run: |
          pip install coverage[toml]
          coverage run testproject/manage.py test fiber_test
      - name: Upload coverage
        if: ${{ matrix.python == 3.8 }}
        uses: codecov/codecov-action@v1
        with:
          name: Python ${{ matrix.python }}
